DELETE FROM public.produtos_ofertas WHERE platform = 'shopee';

INSERT INTO public.produtos_ofertas 
(title, slug, description, image_url, original_price, discount_price, discount_percentage, installments, affiliate_url, platform, category, status, is_featured, is_flash_deal, rating, reviews_count, coupon_code, views_count, clicks_count, expires_at)
VALUES
(
      'KIT3 Un Coqueteis Cream Afrika Marula Chocolate e Choc Branco Bebida Licorosa',
      'kit3-un-coqueteis-cream-afrika-marula-chocolate-e-choc-branco-bebida-licorosa-43852017',
      'Kit com 3 coquetéis cremosos sabor Marula, Chocolate e Chocolate Branco.',
      'https://cf.shopee.sg/file/br-11134207-820l8-mritk0cb4sg719',
      89.90,
      59.90,
      33,
      '2x de R$ 29,95 sem juros',
      'https://s.shopee.com.br/1BMjVwEHAZ',
      'shopee',
      'Doces & Queijos Mineiros',
      'publicado',
      true,
      true,
      4.8,
      350,
      'MINEIRO10',
      3000,
      800,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Queijo Tipo Parmesão Curado Mineiro 400g 850g Queijo Maturado Sabor Marcante para Massas Lanches e T',
      'queijo-tipo-parmesao-curado-mineiro-400g-850g-queijo-maturado-sabor-marcante-par-43851864',
      'Queijo tipo Parmesão curado artesanal mineiro de sabor marcante para massas e petiscos.',
      'https://cf.shopee.sg/file/br-11134201-820m6-mqx4pdnvj95239',
      79.90,
      49.90,
      38,
      '2x de R$ 24,95 sem juros',
      'https://s.shopee.com.br/3VkeHxYKLW',
      'shopee',
      'Doces & Queijos Mineiros',
      'publicado',
      true,
      true,
      4.9,
      495,
      'SHOPEEFRETE',
      3450,
      910,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Kit Provolone Provoleto Queijo Serra Da Canastra 600gr',
      'kit-provolone-provoleto-queijo-serra-da-canastra-600gr-43851781',
      'Kit Provolone Provoleto autêntico da Serra da Canastra defumado.',
      'https://cf.shopee.sg/file/sg-11134201-8257x-ms2pjf36ap6w2f',
      69.90,
      45.90,
      34,
      '2x de R$ 22,95 sem juros',
      'https://s.shopee.com.br/70KWSADWn4',
      'shopee',
      'Doces & Queijos Mineiros',
      'publicado',
      true,
      true,
      5.0,
      640,
      'MINEIRO10',
      3900,
      1020,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Combo 03 Perfumes Mbeec Masculino Tradicional | Alta Fixação e Elegância | Luxo',
      'combo-03-perfumes-mbeec-masculino-tradicional-alta-fixacao-e-elegancia-luxo-43851503',
      'Combo com 3 perfumes masculinos com alta fixação e projeção marcante.',
      'https://cf.shopee.sg/file/sg-11134201-82595-ms2tofr1o2kl43',
      149.90,
      89.90,
      40,
      '2x de R$ 44,95 sem juros',
      'https://s.shopee.com.br/AKayPUuEX4',
      'shopee',
      'Beleza & Perfumaria',
      'publicado',
      true,
      true,
      4.8,
      785,
      'SHOPEEFRETE',
      4350,
      1130,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Café Gourmet Varanda de Vó 500g - 100% Arábica - Torra Média - Moído -',
      'cafe-gourmet-varanda-de-vo-500g-100-arabica-torra-media-moido-42875200',
      'Café artesanal 100% arábica com aroma intenso e notas doces naturais.',
      'https://cf.shopee.sg/file/sg-11134201-82580-mrbzm1v1kzy9b7',
      35.00,
      22.90,
      35,
      '2x de R$ 11,45 sem juros',
      'https://s.shopee.com.br/40gYqtER5C',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      true,
      true,
      4.9,
      930,
      'MINEIRO10',
      4800,
      1240,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'LILYCUTE Esmalte Em Gel Magnético Com Olhos De Gato Vermelho Escuro 7ml Shine Cat Gel Magnético Para',
      'lilycute-esmalte-em-gel-magnetico-com-olhos-de-gato-vermelho-escuro-7ml-shine-ca-42779008',
      'Produto selecionado com excelente avaliação e envio rápido pela Shopee.',
      'https://cf.shopee.sg/file/cn-11134207-820l4-mn41owdik7b741',
      49.90,
      29.90,
      40,
      '2x de R$ 14,95 sem juros',
      'https://s.shopee.com.br/2VrivXF5PX',
      'shopee',
      'Beleza & Perfumaria',
      'publicado',
      true,
      true,
      5.0,
      1075,
      'SHOPEEFRETE',
      5250,
      1350,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Doce de Leite Zero Lactose e Zero Açúcar Adicionado - 430g - Fondant Diet Cremoso Fazenda de Minas',
      'doce-de-leite-zero-lactose-e-zero-acucar-adicionado-430g-fondant-diet-cremoso-fa-41636796',
      'Doce tradicional da fazenda preparado com receita artesanal mineira.',
      'https://cf.shopee.sg/file/br-11134207-81ztc-miuq364vf7r6f5',
      38.00,
      24.90,
      34,
      '2x de R$ 12,45 sem juros',
      'https://s.shopee.com.br/9zxKxz9SxX',
      'shopee',
      'Doces & Queijos Mineiros',
      'publicado',
      true,
      true,
      4.8,
      1220,
      'MINEIRO10',
      5700,
      1460,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Doce de Leite Zero Adição de Açúcar Diet - Gran Boyadjian',
      'doce-de-leite-zero-adicao-de-acucar-diet-gran-boyadjian-41636749',
      'Doce tradicional da fazenda preparado com receita artesanal mineira.',
      'https://cf.shopee.sg/file/sg-11134201-825a6-mq528udt998s9c',
      38.00,
      24.90,
      34,
      '2x de R$ 12,45 sem juros',
      'https://s.shopee.com.br/20v3RBBLAa',
      'shopee',
      'Doces & Queijos Mineiros',
      'publicado',
      true,
      true,
      4.9,
      1365,
      'SHOPEEFRETE',
      6150,
      1570,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Doces e Cocadas Recanto da Serra 660g | 680g – Unitário – Escolha seu Sabor Preferido',
      'doces-e-cocadas-recanto-da-serra-660g-680g-unitario-escolha-seu-sabor-preferido-41623722',
      'Doce tradicional da fazenda preparado com receita artesanal mineira.',
      'https://cf.shopee.sg/file/br-11134207-820l4-moct2yuf826b58',
      38.00,
      24.90,
      34,
      '2x de R$ 12,45 sem juros',
      'https://s.shopee.com.br/50YekOUD5H',
      'shopee',
      'Doces & Queijos Mineiros',
      'publicado',
      true,
      false,
      5.0,
      1510,
      'MINEIRO10',
      6600,
      1680,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Doce de Leite Rocca Café 420g- Doces Mineiros',
      'doce-de-leite-rocca-cafe-420g-doces-mineiros-41525141',
      'Autêntico doce de leite mineiro Rocca harmonizado com café especial.',
      'https://cf.shopee.sg/file/94a783c3fc0e414b7d72293600e5576a',
      45.00,
      32.90,
      27,
      '2x de R$ 16,45 sem juros',
      'https://s.shopee.com.br/20v13ykg7n',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      true,
      false,
      4.8,
      1655,
      'SHOPEEFRETE',
      7050,
      1790,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Doce de Leite (Fondant de Leite) com Ameixa Sem Adição de Açúcar 430 Gramas - Fazenda de Minas',
      'doce-de-leite-fondant-de-leite-com-ameixa-sem-adicao-de-acucar-430-gramas-fazend-41525086',
      'Doce tradicional da fazenda preparado com receita artesanal mineira.',
      'https://cf.shopee.sg/file/br-11134207-7r98o-m9c026slb8jmf1',
      38.00,
      24.90,
      34,
      '2x de R$ 12,45 sem juros',
      'https://s.shopee.com.br/6L40DpoTGA',
      'shopee',
      'Doces & Queijos Mineiros',
      'publicado',
      true,
      false,
      4.9,
      1800,
      'MINEIRO10',
      7500,
      1900,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Doces Zero Açúcar 430g - Doce de Leite, Goiabada, Abóbora, Cocadas, Zero Lactose - Fazenda de Minas',
      'doces-zero-acucar-430g-doce-de-leite-goiabada-abobora-cocadas-zero-lactose-fazen-41524615',
      'Doce tradicional da fazenda preparado com receita artesanal mineira.',
      'https://cf.shopee.sg/file/br-11134207-820m4-mr4q3r78uyv956',
      38.00,
      24.90,
      34,
      '2x de R$ 12,45 sem juros',
      'https://s.shopee.com.br/9fKSBbXT87',
      'shopee',
      'Doces & Queijos Mineiros',
      'publicado',
      true,
      false,
      5.0,
      1945,
      'SHOPEEFRETE',
      7950,
      2010,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Doces Fazenda de Minas Sem Adição de Açúcar 400g a 430g | Doce de Leite, Cocada, Bananada, Goiabada ',
      'doces-fazenda-de-minas-sem-adicao-de-acucar-400g-a-430g-doce-de-leite-cocada-ban-41524230',
      'Doce tradicional da fazenda preparado com receita artesanal mineira.',
      'https://cf.shopee.sg/file/br-11134207-820me-msbqmlwkwhdw8a',
      38.00,
      24.90,
      34,
      '2x de R$ 12,45 sem juros',
      'https://s.shopee.com.br/W6DGV8Qgx',
      'shopee',
      'Doces & Queijos Mineiros',
      'publicado',
      true,
      false,
      4.8,
      2090,
      'MINEIRO10',
      8400,
      2120,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Doce de leite Aviação 400g Envio Super Rápido',
      'doce-de-leite-aviacao-400g-envio-super-rapido-41523823',
      'Tradicional doce de leite Aviação cremoso de altíssima qualidade.',
      'https://cf.shopee.sg/file/br-11134207-820m7-mo6aec02x0qo8c',
      36.00,
      24.90,
      31,
      '2x de R$ 12,45 sem juros',
      'https://s.shopee.com.br/AUtZANDwjw',
      'shopee',
      'Doces & Queijos Mineiros',
      'publicado',
      true,
      false,
      4.9,
      2235,
      'SHOPEEFRETE',
      8850,
      2230,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Garrafa Térmica De Café 1L / 1,9L com Pressão Verona Ideal para Café Chá Tererê Água Apertar Hotel C',
      'garrafa-termica-de-cafe-1l-1-9l-com-pressao-verona-ideal-para-cafe-cha-terere-ag-41500211',
      'Garrafa térmica Verona com sistema de pressão para café e chá quente.',
      'https://cf.shopee.sg/file/br-11134207-820lm-mr1sv5ngfo5hfc',
      99.90,
      58.90,
      41,
      '2x de R$ 29,45 sem juros',
      'https://s.shopee.com.br/gPd1WeFjs',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      true,
      false,
      5.0,
      2380,
      'MINEIRO10',
      9300,
      2340,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Café Especial Torrado e Moído 250g Café Premiado 100% Arábica Orfeu Pó de Café',
      'cafe-especial-torrado-e-moido-250g-cafe-premiado-100-arabica-orfeu-po-de-cafe-41500104',
      'Café especial premiado 100% Arábica Orfeu, torrado e moído com notas equilibradas.',
      'https://cf.shopee.sg/file/sg-11134201-22110-g6otil5jqdjv83',
      42.00,
      29.90,
      29,
      '2x de R$ 14,95 sem juros',
      'https://s.shopee.com.br/2VrHCput7S',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      true,
      false,
      4.8,
      2525,
      'SHOPEEFRETE',
      9750,
      2450,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Café caseiro artesanal 500gr Árabica 100% torrado e moído- Café do Vô',
      'cafe-caseiro-artesanal-500gr-arabica-100-torrado-e-moido-cafe-do-vo-41500055',
      'Café artesanal 100% arábica com aroma intenso e notas doces naturais.',
      'https://cf.shopee.sg/file/br-11134207-81z1k-mfinlbzdrd342f',
      35.00,
      22.90,
      35,
      '2x de R$ 11,45 sem juros',
      'https://s.shopee.com.br/2VrHCj1q8z',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      false,
      false,
      4.9,
      2670,
      'MINEIRO10',
      10200,
      2560,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'CAFÉ EM GRÃOS TORRADO 100% ARÁBICA grãos selecionados-CAFÉ DO VÔ torra clássica',
      'cafe-em-graos-torrado-100-arabica-graos-selecionados-cafe-do-vo-torra-classica-41500028',
      'Café artesanal 100% arábica com aroma intenso e notas doces naturais.',
      'https://cf.shopee.sg/file/br-11134207-7r98o-mddr5ss8icch2c',
      35.00,
      22.90,
      35,
      '2x de R$ 11,45 sem juros',
      'https://s.shopee.com.br/2LXr0KVQy9',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      false,
      false,
      5.0,
      2815,
      'SHOPEEFRETE',
      10650,
      2670,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Café Serra Nobre Gourmet 250g 100% Arábica – Torrado e Moído Torra Média | Montanhas Capixabas',
      'cafe-serra-nobre-gourmet-250g-100-arabica-torrado-e-moido-torra-media-montanhas--41499669',
      'Café artesanal 100% arábica com aroma intenso e notas doces naturais.',
      'https://cf.shopee.sg/file/sg-11134201-8258o-ms4ljevildzb98',
      35.00,
      22.90,
      35,
      '2x de R$ 11,45 sem juros',
      'https://s.shopee.com.br/AKa8Wh5CQw',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      false,
      false,
      4.8,
      2960,
      'MINEIRO10',
      11100,
      2780,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Spray de Azeite Borrifador Oleo Vinagre Pulverizador Culinário + Saleiro',
      'spray-de-azeite-borrifador-oleo-vinagre-pulverizador-culinario-saleiro-41499632',
      'Pulverizador prático para óleo, azeite e vinagre com dosagem perfeita.',
      'https://cf.shopee.sg/file/br-11134207-820m3-mn787p2qjri953',
      39.90,
      21.90,
      45,
      '2x de R$ 10,95 sem juros',
      'https://s.shopee.com.br/7Ad6klkTqr',
      'shopee',
      'Utensílios & Café',
      'publicado',
      false,
      false,
      4.9,
      3105,
      'SHOPEEFRETE',
      11550,
      2890,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Spray Borrifador de Azeite Pulverizador automático para cozinha de vidro água Óleo Vinagre',
      'spray-borrifador-de-azeite-pulverizador-automatico-para-cozinha-de-vidro-agua-ol-41499571',
      'Pulverizador prático para óleo, azeite e vinagre com dosagem perfeita.',
      'https://cf.shopee.sg/file/br-11134207-820l4-mo05qkf82a6ab6',
      39.90,
      21.90,
      45,
      '2x de R$ 10,95 sem juros',
      'https://s.shopee.com.br/8plKjc5VyB',
      'shopee',
      'Utensílios & Café',
      'publicado',
      false,
      false,
      5.0,
      3250,
      'MINEIRO10',
      12000,
      3000,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Café Aviação Superior 100% Arábica Torrado e Moído Torra Média 500g Sabor Tradicional I Extra Forte',
      'cafe-aviacao-superior-100-arabica-torrado-e-moido-torra-media-500g-sabor-tradici-41499516',
      'Tradicional doce de leite Aviação cremoso de altíssima qualidade.',
      'https://cf.shopee.sg/file/br-11134207-820lf-mqsd03gsjmdda4',
      36.00,
      24.90,
      31,
      '2x de R$ 12,45 sem juros',
      'https://s.shopee.com.br/8fRuXFPMcV',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      false,
      false,
      4.8,
      3395,
      'SHOPEEFRETE',
      12450,
      3110,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Café Alfari 500g Arábica Gourmet Qualidade Superior Torrado Moído',
      'cafe-alfari-500g-arabica-gourmet-qualidade-superior-torrado-moido-41499275',
      'Café artesanal 100% arábica com aroma intenso e notas doces naturais.',
      'https://cf.shopee.sg/file/br-11134207-820ly-mmiwm9y2xla876',
      35.00,
      22.90,
      35,
      '2x de R$ 11,45 sem juros',
      'https://s.shopee.com.br/BTMPQIZa1',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      false,
      false,
      4.9,
      3540,
      'MINEIRO10',
      12900,
      3220,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Café L''or Solúvel Liofilizado Pote Vidro Com Tampa Hermética',
      'cafe-l-or-soluvel-liofilizado-pote-vidro-com-tampa-hermetica-41499059',
      'Café artesanal 100% arábica com aroma intenso e notas doces naturais.',
      'https://cf.shopee.sg/file/br-11134207-820m7-mr6c4mhvmt52b2',
      35.00,
      22.90,
      35,
      '2x de R$ 11,45 sem juros',
      'https://s.shopee.com.br/7psnXDNb5H',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      false,
      false,
      5.0,
      3685,
      'SHOPEEFRETE',
      13350,
      3330,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Baggio Café - Café Torrado e Moído Aromas Chocolate Trufado 250g',
      'baggio-cafe-cafe-torrado-e-moido-aromas-chocolate-trufado-250g-41499031',
      'Café aromático Baggio com toque aveludado de chocolate trufado.',
      'https://cf.shopee.sg/file/br-11134207-7r98o-m6dyejgqt4rr40',
      39.90,
      26.90,
      33,
      '2x de R$ 13,45 sem juros',
      'https://s.shopee.com.br/4fvllItoQa',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      false,
      false,
      4.8,
      3830,
      'MINEIRO10',
      13800,
      3440,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Café Italle Aromatizado Trufado e Caramelo Café 500g',
      'cafe-italle-aromatizado-trufado-e-caramelo-cafe-500g-41498997',
      'Café artesanal 100% arábica com aroma intenso e notas doces naturais.',
      'https://cf.shopee.sg/file/sg-11134201-824g6-mfimnw9ef024d8',
      35.00,
      22.90,
      35,
      '2x de R$ 11,45 sem juros',
      'https://s.shopee.com.br/9pdruedi67',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      false,
      false,
      4.9,
      3975,
      'SHOPEEFRETE',
      14250,
      3550,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Café Torrado E Moído Café em Pó Café Tradicional Moido 500g',
      'cafe-torrado-e-moido-cafe-em-po-cafe-tradicional-moido-500g-41498968',
      'Café artesanal 100% arábica com aroma intenso e notas doces naturais.',
      'https://cf.shopee.sg/file/br-11134207-820lr-mq3e8bjeps0007',
      35.00,
      22.90,
      35,
      '2x de R$ 11,45 sem juros',
      'https://s.shopee.com.br/80CDj7kGDh',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      false,
      false,
      5.0,
      4120,
      'MINEIRO10',
      14700,
      3660,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'CAFÉ OURO PRETO FORTE 100% ARÁBICA TORRA ESCURA',
      'cafe-ouro-preto-forte-100-arabica-torra-escura-41498140',
      'Café artesanal 100% arábica com aroma intenso e notas doces naturais.',
      'https://cf.shopee.sg/file/br-11134207-820lr-ms1j2t3sfoxy05',
      35.00,
      22.90,
      35,
      '2x de R$ 11,45 sem juros',
      'https://s.shopee.com.br/4qFBwgC4OM',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      false,
      false,
      4.8,
      4265,
      'SHOPEEFRETE',
      15150,
      3770,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Copo Térmico 500ml Isolado a Vácuo | Mantém Temperatura | Leve e Fácil Transporte',
      'copo-termico-500ml-isolado-a-vacuo-mantem-temperatura-leve-e-facil-transporte-41498051',
      'Copo térmico em inox com isolamento a vácuo para bebidas quentes e geladas.',
      'https://cf.shopee.sg/file/sg-11134201-82581-mr9xn70toop003',
      59.00,
      34.90,
      41,
      '2x de R$ 17,45 sem juros',
      'https://s.shopee.com.br/9zxI5wgavF',
      'shopee',
      'Utensílios & Café',
      'publicado',
      false,
      false,
      4.9,
      4410,
      'MINEIRO10',
      15600,
      3880,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Caneca Copo Café Coffee Isolado Termico de Aço Inoxidável à Prova de Vazamento 510ML',
      'caneca-copo-cafe-coffee-isolado-termico-de-aco-inoxidavel-a-prova-de-vazamento-5-41498023',
      'Café artesanal 100% arábica com aroma intenso e notas doces naturais.',
      'https://cf.shopee.sg/file/br-11134207-820lq-mo178h0xijgk43',
      35.00,
      22.90,
      35,
      '2x de R$ 11,45 sem juros',
      'https://s.shopee.com.br/70JgWJz6b2',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      false,
      false,
      5.0,
      4555,
      'SHOPEEFRETE',
      16050,
      3990,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Moedor Elétrico Multifuncional Café Grãos Especiarias 4 Lâminas Aço Inoxidável 110V',
      'moedor-eletrico-multifuncional-cafe-graos-especiarias-4-laminas-aco-inoxidavel-1-41497989',
      'Moedor elétrico multifuncional com lâminas de aço inox para moagem rápida.',
      'https://cf.shopee.sg/file/br-11134207-820l5-moqsqxed8v0l08',
      89.90,
      49.90,
      44,
      '2x de R$ 24,95 sem juros',
      'https://s.shopee.com.br/40g4wh4YPx',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      false,
      false,
      4.8,
      4700,
      'MINEIRO10',
      16500,
      4100,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Copo de Café Térmico Portátil 410ml｜Com Tampa Antivazamento e Display LED',
      'copo-de-cafe-termico-portatil-410ml-com-tampa-antivazamento-e-display-led-41497964',
      'Copo térmico inteligente com sensor de temperatura em display LED touch.',
      'https://cf.shopee.sg/file/sg-11134201-825au-mqqhktezh6v691',
      69.90,
      38.90,
      44,
      '2x de R$ 19,45 sem juros',
      'https://s.shopee.com.br/7KwWuhhdEA',
      'shopee',
      'Cafés & Gourmet',
      'publicado',
      false,
      false,
      4.9,
      4845,
      'SHOPEEFRETE',
      16950,
      4210,
      timezone('utc'::text, now() + interval '10 days')
    ),
(
      'Caneca Misturadora Automática Elétrica USB Recarregável 380ml',
      'caneca-misturadora-automatica-eletrica-usb-recarregavel-380ml-41497909',
      'Caneca automática que mistura café, leite e suplementos com 1 toque.',
      'https://cf.shopee.sg/file/br-11134207-820md-mryxxvrh16h2df',
      59.90,
      34.90,
      42,
      '2x de R$ 17,45 sem juros',
      'https://s.shopee.com.br/8Kp46AZung',
      'shopee',
      'Utensílios & Café',
      'publicado',
      false,
      false,
      5.0,
      4990,
      'MINEIRO10',
      17400,
      4320,
      timezone('utc'::text, now() + interval '10 days')
    );